### ISSUE TITLE
go bindings test fail

### ISSUE THREAD

**Issue by nwaples** [CloudNativeDataPlane/cndp#174]
lang/go/bindings/cne$ ./run_test
=== RUN   TestStarting
--- PASS: TestStarting (0.33s)
=== RUN   TestGetChannel
=== RUN   TestGetChannel/TestLoopback
=== RUN   TestGetChannel/TestLoopback#01
--- PASS: TestGetChannel (0.00s)
    --- PASS: TestGetChannel/TestLoopback (0.00s)
    --- PASS: TestGetChannel/TestLoopback#01 (0.00s)
=== RUN   TestRxBurst
=== RUN   TestRxBurst/TestRxBurst
cne.test: ../lib/core/cne/cne.c:28: cne_id: Assertion `per_thread__cne != NULL' failed.
SIGABRT: abort
PC=0x7fdce9f0000b m=3 sigcode=18446744073709551610
signal arrived during cgo execution

The same thing happens when I run OpenWIthConfig() in my own code.

**Comment by KeithWiles** [comment]
Thank, It appears the register call is not being done for the thread that is running and calling into CNDP. Let me look at the problem.

**Comment by KeithWiles** [comment]
I believe I have a quick for this issue. What happened was we add an assert to the cne_id() routine to validate the current thread local storage was valid. The test code was not calling RegisterThread in all cases or calling the routine twice in the same go thread which can corrupt the TLS pointer. The fwd example application also did not call RegisterThread and UnregisterThread correctly.

Each Go thread that is sending or receiving traffic or alloc/free pktmbuf's must call RegisterThread() once and UnregisterThread as the go thread dies.

Here is the PR: https://github.com/CloudNativeDataPlane/cndp/pull/179

Please have a look and give it a review/test.

**Comment by nwaples** [comment]
I get this error on run_test

./system_test.go:10:2: imported and not used: "strconv"

but if I remove the import, all seems to be ok.

**Comment by KeithWiles** [comment]
Somehow I missed that one :-( I will update the PR.

**Comment by KeithWiles** [comment]
I think we can close this one, correct?

**Comment by nwaples** [comment]
yes
