### ISSUE TITLE
newer versions of libbpf 0.8.0 or libxdp

### ISSUE THREAD

**Issue by KeithWiles** [CloudNativeDataPlane/cndp#183]
It appears while adding txgen latency support, the packet data offset with pktmbuf_mtod() is not pointing to the start of packet data as expected. It appears libbpf 0.6.0 behaves correctly and we need to move to libxdp to verify the problem exists.

**Comment by KeithWiles** [comment]
Can we close this issue?

**Comment by maryamtahhan** [comment]
Yes- We can close after the testing and validation done with https://github.com/CloudNativeDataPlane/cndp/pull/189
