### ISSUE TITLE
Update the Ansible playbook

### ISSUE THREAD

**Issue by KeithWiles** [CloudNativeDataPlane/cndp#228]
**Difficulty**: Easy to Medium

Update the CNDP [Ansible playbook](https://github.com/CloudNativeDataPlane/cndp/tree/main/ansible) to make sure it support for Fedora installs. 

The playbook needs to be updated to support libbpf and libxdp as the new libxdp contains the XSK APIs which were deprecated in libbpf , but libbpf is still required.

**Comment by maryamtahhan** [comment]
I would add the Ansible playbook also needs to be updated to support the installation of libxdp (for both Ubuntu and Fedora...) maybe a separate issue? I can create one if we think it is

**Comment by KeithWiles** [comment]
I added your comment to the issue, thanks.

**Comment by haoruan** [comment]
CNDP_Team2 working on this
