### ISSUE TITLE
Rework the test-cne testing infrastructure

### ISSUE THREAD

**Issue by KeithWiles** [CloudNativeDataPlane/cndp#234]
**Difficulty**: Easy

Enhance the test-cne infrastructure to be more consistent or easier to use. Need all of the tests to look similar and produce similar output.

For [example](https://github.com/CloudNativeDataPlane/cndp/blob/main/test/testcne/graph_test.c) to show this test is different then the others. This test uses printf and not the tst_info() or tst_error() type APIs, these need to be cleaned up to use the correct APIs from the tst_ XXX library.

**Comment by byron-marohn** [comment]
Oof, didn't notice that pushing commits to a fork that referenced this number would leave comments here. I think we're done generating noise here for now. 

We've addressed several of the improvements suggested here for test files, but there are still some that need doing which someone else is welcome to work on.

**Comment by KeithWiles** [comment]
I think the major changes have been done and we can open a new issue later to address any other issues.
