### ISSUE TITLE
cndpfwd: cleanup if we fail when parsing args

### ISSUE THREAD

**Issue by maryamtahhan** [CloudNativeDataPlane/cndp#267]
Difficulty: Easy to Medium

Some additional cleanup is needed to ensure that malloc'ed/mmap'd memory is freed when we return in error during argument parsing in: https://github.com/CloudNativeDataPlane/cndp/blob/main/examples/cndpfwd/parse-args.c

**Comment by haoruan** [comment]
CNDP_Team2 working on this
