### ISSUE TITLE
IPv6 roadmap

### ISSUE THREAD

**Issue by lperkov** [CloudNativeDataPlane/cndp#274]
Hello there!

I am interested in finding out more information about the timeline for IPv6 support. If this becomes available, we would be eager to test it out for these use cases:

1. lw4o6 (RFC 7596) including both:
* AFTR
* B4

2. Keyed IPv6 tunnel (RFC 8159)

We would be happy to contribute this code back as the example projects.

Any feedback would be greatly appreciated.

**Comment by pktgen** [comment]
At this point we do not have a timeline for IPv6 and would like to see a PR/example project to add this support to CNDP.

**Comment by lperkov** [comment]
Based on feedback from another issue, I'm not sure if lwIP is suitable for this project. Did you develop the current IPv4 stack from scratch? 

We can commit to adding a feature on top of existing IPv6, but developing the entire IPv6 stack would be something that we could not complete in a timely manner.
