### ISSUE TITLE
lwIP question

### ISSUE THREAD

**Issue by lperkov** [CloudNativeDataPlane/cndp#275]
Have any evaluations been done on using lwIP as an alternative to the IP stack that was created from scratch?

If so, why was this design chosen instead? Was it due to performance reasons?

**Comment by pktgen** [comment]
Yes, we did have lwIP example and it was a quick little project, but the performance was very low. Plus lwIP does not have a lot features. We removed the lwIP example, which you should be able to find in the git logs if you want to look at the example.

**Comment by lperkov** [comment]
Thanks!
