### ISSUE TITLE
service chaining

### ISSUE THREAD

**Issue by lperkov** [CloudNativeDataPlane/cndp#276]
Creating a chain of virtual network functions (VNFs) is an intriguing topic. Is this something that Kubernetes stack would take care of?

Are there any methods that could be used to achieve this without compromising performance but in a modular way and not involving Kubernetes?

IMHO this framework does have a great potential to be used outside of Kubernetes.

**Comment by pktgen** [comment]
I guess it is possible to do the chaining of VNFs in a number of ways, but I do not have any suggestions without K8s.

**Comment by lperkov** [comment]
Okay, thanks!
