### ISSUE TITLE
cnet: ip4_forward node fib lookup tightly coupled with arp entry

### ISSUE THREAD

**Issue by maryamtahhan** [CloudNativeDataPlane/cndp#321]
Currently with the ip4_forward node we call `fib_info_lookup` with the arp fib table. We need to use the [route fib table](https://github.com/CloudNativeDataPlane/cndp/blob/main/lib/cnet/cnet/cnet.h#LL48C1-L48C31) in conjunction with the arp table.

```
fi          = cnet->arp_finfo;
....
 if (unlikely(fib_info_lookup(fi, ip4, (void **)arp, 4) > 0)) {
 ...
 ```
 
with [fib_info_lookup](https://github.com/CloudNativeDataPlane/cndp/blob/main/lib/cnet/incs/cnet_fib_info.h#LL306C1-L330C2) if we rely so much on the arp FIB table and not route FIB the ip4_forward node won't know what to do with the traffic that doesn't have an arp entry and the node will assign it to the arp_request node.... the suggestion is to do an arp lookup first, if that fails - try to find the next hop info from the route fib... we may then need to do an arp lookup on that next hop...

**Comment by maryamtahhan** [comment]
Or Even better should check both ARP and ROUTE FIB

**Comment by maryamtahhan** [comment]
Hi @KeithWiles 

So I've been looking into this... the fib lookup isn't really the issue... The issue is that the arp requests aren't really being generated from the arp request node?

So what that ARP request node is doing today if I understand correctly is that [arp_request_process_mbuf](https://github.com/CloudNativeDataPlane/cndp/blob/main/lib/cnet/arp/arp_request.c#L37) is trying to punt the packet to the kernel... but it seems like nothing is happening? It feels like the [offset](https://github.com/CloudNativeDataPlane/cndp/blob/main/lib/cnet/arp/arp_request.c#L47) is not correct if I compare it to the normal punt node. I actually even tried just replacing the arp request node with the punt node from ip_forward with no success....

The other option is to change the arp request node to really generate an arp request and sending out of an interface using something like

```
static __cne_always_inline cne_edge_t
arp_request_process_mbuf(struct cne_node *node, pktmbuf_t *mbuf)
{
    arp_request_node_ctx_t *ctx = (arp_request_node_ctx_t *)node->ctx;

    if (ctx->s >= 0) {
        struct cne_ipv4_hdr *ip4;
        struct sockaddr_ll sll = {0};
        char ifname[24];
        const unsigned char ether_broadcast_addr[]=  {0xff,0xff,0xff,0xff,0xff,0xff};

        ip4 = pktmbuf_mtod(mbuf, struct cne_ipv4_hdr *);
        pktdev_get_name_by_port(mbuf->lport, ifname, 24);

        sll.sll_family   = AF_PACKET;
        sll.sll_protocol = htons(ETH_P_ARP);
        sll.sll_ifindex  = if_nametoindex(ifname);
        sll.sll_halen    = ETHER_ADDR_LEN;
        memcpy(sll.sll_addr, ether_broadcast_addr, ETHER_ADDR_LEN);


        struct ether_arp req;

        req.arp_hrd=htons(ARPHRD_ETHER);
        req.arp_pro=htons(ETH_P_IP);
        req.arp_hln=ETHER_ADDR_LEN;
        req.arp_pln=sizeof(in_addr_t);
        req.arp_op=htons(ARPOP_REQUEST);
        memset(&req.arp_tha,0,sizeof(req.arp_tha));

        memcpy(&req.arp_tpa, &ip4->dst_addr, sizeof(req.arp_tpa));

        if (sendto(ctx->s, &req, sizeof(req), 0, (struct sockaddr *)&sll, sizeof(sll)) < 0)
            CNE_WARN("Failed to send packets: %s\n", strerror(errno));
    }

    return ARP_REQUEST_NEXT_PKT_DROP;
}

...

static int
arp_request_node_init(const struct cne_graph *graph __cne_unused, struct cne_node *node)
{
    arp_request_node_ctx_t *ctx = (arp_request_node_ctx_t *)node->ctx;

    ctx->s = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_ALL));
    if (ctx->s < 0)
        CNE_ERR_RET("Failed to open RAW socket\n");

    return 0;
}

```

the issue what that code snippet is that we are sending the arp request back out on the interface the original packet came in... so I would need to change it to send the arp request probably out of all attached interfaces to cnet? 

It's hard to track the packet through the normal socket (when using the punt node), were you using `ss`?

**Comment by maryamtahhan** [comment]
so I've update the arp-request node to send an ARP request out of all the interfaces attached to cnet in https://github.com/CloudNativeDataPlane/cndp/pull/336

I still need to make a change so that if we know the route to an address we are good to send it out the right interface rather than just doing the arp table lookup

**Comment by KeithWiles** [comment]
Does the ARP table in the kernel get updated when the ARP request is sent from within CNET?

The kernel is suppose to send the arp request and update the kernel ARP table which gives CNET a netlink message.

**Comment by maryamtahhan** [comment]
> Does the ARP table in the kernel get updated when the ARP request is sent from within CNET?

I thought it did but I will double check... if it doesn't then we can just ignore it... :) I will forever have an arp request through a socket example :) 

> The kernel is suppose to send the arp request and update the kernel ARP table which gives CNET a netlink message.

Ok - yeah that makes sense. So I think the reason no ARPs were being sent out in the case we are debugging is because there's a route entry to a network that's not directly connected to us. So the packet is getting passed to the kernel, kernel knows where to send it and (it's not a locally connected network so no ARPs) and it just forwards the packet.

These are the cnet issues atm:
1. I never see ip neigh inside cnet even though there's entries in the linux kernel, so we need to look at this side of the netlink info, something isn't being triggered appropriately?

2. We need to extend the parsing of the route information from and kernel and we also need to extend our fib to hold the `via` information for routes that include the `via` information. so we arp on the `via address`

```
[]# ip route
default via 172.20.0.1 dev eth0 
172.19.0.0/16 nhid 14 via 172.20.0.3 dev eth0 proto ospf metric 20  <<<<<< we need to resolve this
172.20.0.0/16 dev eth0 proto kernel scope link src 172.20.0.2 <<<< we resolve this fine... 
172.21.0.0/16 dev eth1 proto kernel scope link src 172.21.0.3 

[]# ip neigh
172.20.0.2 dev eth1 lladdr 02:42:ac:14:00:02 STALE proto zebra
```

```
** Version: CNDP 23.06.0, Command Line Interface
CNDP-cli:/> ip neigh
CNDP-cli:/> ip route
Route Table for CNET on lcore 0
  Nexthop           Mask               IF  Gateway           Metric Timeout   Netdev
  172.19.0.3        255.255.255.255     0  0.0.0.0               16       0   eth0:0
  172.20.0.3        255.255.255.255     1  0.0.0.0               16       0   eth1:0
  172.19.0.0        255.255.0.0         0  0.0.0.0               16       0   eth0:0
  172.20.0.0        255.255.0.0         1  0.0.0.0               16       0   eth1:0
  172.21.0.0        255.255.0.0         1  0.0.0.0               16       0   eth1:0
```

Looking at the info in cnet today the only piece of info we are missing to successfully forward a packet to in indirect network is the destination mac address for the next hop device. and that's why we need the via info and to arp on that via address. 

Ip neigh we can probably fixup separately

**Comment by KeithWiles** [comment]
Adding the via information and neighbor in the netlink code is the right direction. The netlink code only deals with local interfaces as I prune the other out and maybe it needs to start looking at everything.

**Comment by maryamtahhan** [comment]
So the fix for this is here: https://github.com/CloudNativeDataPlane/cndp/compare/main...maryamtahhan:cndp:hotfix_ip_forward

We had the `via` info just weren't pushing it to the fib... so in that code ip_forward tries to see if the address is for a local network, if not, it looks up the gateway and then looks up the arp entry for the Gateway...

I would like to cleanup that code as it's a bit ugly ATM.. but that's the fix anyway :)

**Comment by KeithWiles** [comment]
Great work!
