### ISSUE TITLE
Use wireguard(with cndp) as the client to connect to the wireguard server supported by the normal Linux kernel?

### ISSUE THREAD

**Issue by liuzhen111** [CloudNativeDataPlane/cndp#323]
Excuse me, can I use WireGuard CNDP as the client to connect to the wireguard server supported by the normal Linux kernel? 
Example:  
Wireguard cndp<———->normal WireGuard server. 
  
    I am currently testing in this way and cannot receive any data packets on the server.

**Comment by KeithWiles** [comment]
I believe this works, but the person that can help is out of the office 27-28 and most likely will not reply till next week.

I am sure he tested this type of setup. Make sure the MAC addresses are correct for the Linux server or place the Linux server interface into promiscuous mode e.g. 'ifconfig eth0 promisc' this step is not normally required, but just to eliminate the MAC addresses.

**Comment by liuzhen111** [comment]
I used ubuntu server 22.04.2 for my tests.
The kernel version is 5.15.0-60-generic.,
libbpf is v0.6.1,
Apart from setting the promiscuous mode of the NIC, what else should I pay attention to?

**Comment by liuzhen111** [comment]
debug:
2023-06-27T14:48:04Z DEBUG wireguard_rs::wireguard::workers] TUN worker, IP packet of 84 bytes (MTU = 1280)
[2023-06-27T14:48:04Z DEBUG wireguard_rs::wireguard::workers] TUN worker, router returned Err(NoCryptoKeyRoute)
[2023-06-27T14:48:05Z DEBUG wireguard_rs::wireguard::workers] TUN worker, IP packet of 84 bytes (MTU = 1280)
[2023-06-27T14:48:05Z DEBUG wireguard_rs::wireguard::workers] TUN worker, router returned Err(NoCryptoKeyRoute)

**Comment by manojgop** [comment]
Hi @liuzhen111  - I verified that it works `wireguard cndp <--> linux normal wireguard`. Does `wireguard default (without cndp) <--> linux normal wireguard` and `wireguard cndp <--> wireguard cndp` work for you ? I ran wireguard cndp using `./src/platform/linux/cndp/cndprustwg.sh`. Did you set ethtool rules for wireguard cndp for the required wg endpoint interface to send/recv packets to a specific qid ?

**Comment by liuzhen111** [comment]
@manojgop   Hello, the network topology  is:  
Server A(with cndp) <--> Server B(without cndp)

I have used ethtool to queue the specified traffic as follows on Server A:
ethtool -U ens6f1 flow-type udp4  src-ip 192.168.60.2  dst-ip 192.168.60.1    action 1  loc 1
ethtool -U ens6f1 flow-type udp4  src-ip 192.168.60.1  dst-ip 192.168.60.2    action 2  loc 2

192.168.60.2 is an intel x710 network adapter on ServerA (ubuntu 20).
192.168.60.1 is the ip address of a remote server B using a kvm VM (ubuntu 20).

**Comment by manojgop** [comment]
Need more information. Can you share output of `sudo wg` on both systems . Also the contents of fwd.jsonc file used with CNDP

**Comment by liuzhen111** [comment]
@manojgop  Hello brother, I have sent relevant configuration files to your email address: manoj.gopalakrishnan@intel.com
sudo wg output information display is normal.

**Comment by liuzhen111** [comment]
<img width="1225" alt="image" src="https://github.com/CloudNativeDataPlane/cndp/assets/13791154/629154c2-a625-4273-9f92-a2c7569ca8e7">
[fwd.txt](https://github.com/CloudNativeDataPlane/cndp/files/11950243/fwd.txt)
@manojgop

**Comment by manojgop** [comment]
> @manojgop Hello brother, I have sent relevant configuration files to your email address: [manoj.gopalakrishnan@intel.com](mailto:manoj.gopalakrishnan@intel.com) sudo wg output information display is normal.

Some email attachment got blocked. Just to confirm - Did you set the private keys in local wg interface ? Below is the configuration in my setup with CNDP wireguard and Linux kernel wireguard

```
Endpoint 1 (CNDP Wireguard)
=============================

$ sudo wg
interface: rsuwg0
  public key: Gj/rmlfLyAtS/4RK9oq6WB6gDyKcQmgiKYwosIqJ9HA=
  private key: (hidden)

peer: DV/f0jntATrrng/D7jVmqBz6IFlHWjPT/QsmhDut5Es=
  endpoint: 48.0.0.155:5500
  allowed ips: 10.0.4.2/32
  
$ip addr show enp134s0
5: enp134s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 xdp/id:654 qdisc mq state UP group default qlen 1000
    link/ether 40:a6:b7:78:3f:ec brd ff:ff:ff:ff:ff:ff
    inet 48.0.0.154/24 scope global enp134s0
       valid_lft forever preferred_lft forever
    inet6 fe80::42a6:b7ff:fe78:3fec/64 scope link
       valid_lft forever preferred_lft forever  
  
ethtool rules
sudo ethtool -N enp134s0 flow-type udp4 src-ip 48.0.0.155 dst-ip 48.0.0.154 action 23
sudo ethtool -N enp134s0 flow-type udp4 src-ip 48.0.0.154 dst-ip 48.0.0.155 action 33
  
  
  
Endpoint 2 (Linux Kernel Wireguard)
=====================================
$ sudo wg
interface: wg0
  public key: DV/f0jntATrrng/D7jVmqBz6IFlHWjPT/QsmhDut5Es=
  private key: (hidden)
  listening port: 5500

peer: Gj/rmlfLyAtS/4RK9oq6WB6gDyKcQmgiKYwosIqJ9HA=
  endpoint: 48.0.0.154:5400
  allowed ips: 10.0.4.1/32
  
$ip addr show enp134s0
136: enp134s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 40:a6:b7:68:95:d4 brd ff:ff:ff:ff:ff:ff
    inet 48.0.0.155/24 scope global enp134s0
       valid_lft forever preferred_lft forever

ethtool rules
sudo ethtool -N enp134s0 flow-type udp4 src-ip 48.0.0.154 dst-ip 48.0.0.155 action 23
sudo ethtool -N enp134s0 flow-type udp4 src-ip 48.0.0.155 dst-ip 48.0.0.154 action 33
```

**Comment by liuzhen111** [comment]
#!/bin/bash
# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2019-2021 Intel Corporation.

# Run this script as sudo
# Usage: ./cndprustwg.sh [debug|release] [cndp-packet|cndp-ping|wireguard-rs].
# Wireguard CNDP Root folder
WG_ROOT="/var/by/wireguard-rs"
# Build type (debug/release). Use release by default.
BUILD=${1:-release}
# Build type (debug/release). Use release by default.
EXE=${2:-wireguard-rs}
# Set private key file.
# Private/Public key should be generated once before running this script
# using following commands.
# 1) Private key -> "sudo wg genkey > rsuwgprivate"
# 2) Public key  -> "wg pubkey < rsuwgprivate > rsuwgpublic"
PRIVATE_KEY="/etc/private-key"
# Wireguard MTU size.
WG_MTU=1280
# Wirguard interface local ip.
WG_LOCAL_IP=10.5.5.7
# Wireguard local listen port.
WG_LOCAL_LISTEN_PORT=5400
# Wirguard interface remote peer ip.
WG_PEER_IP=10.5.5.1
# Wireguard remote peer listen port.
WG_PEER_LISTEN_PORT=8899
# Wireguard remote peer endpoint ip.
WG_PEER_ENDPOINT_IP=192.168.60.1
# Wireguard remote peer endpoint.
WG_PEER_ENDPOINT=$WG_PEER_ENDPOINT_IP:$WG_PEER_LISTEN_PORT
# Peer public key (base64 encoded)
WG_PEER_PUBLIC_KEY="we1jHCODRo0Dr9B57pxxJV+Kkb5v8n6zWyoGI3fptkw="


# Delete existing interface
sudo ip link del rsuwg0
# Wait for interface to go down.
sleep 3
# Copy wg_cndp.toml file to target directory containing the executable.
cp $WG_ROOT/src/platform/linux/cndp/wg_cndp.toml $WG_ROOT/target/$BUILD/wg_cndp.toml
# Start and configure wireguard
if [ "$BUILD" == "debug" ]; then
	RUST_LOG_VAL=debug
else
	RUST_LOG_VAL=info
fi
# Check the binary to execute
if [ "$EXE" == "cndp-ping" ]; then
	RUST_EXE=cndp-ping
	ARGS="--disable-drop-privileges --device rsuwg0 --local $WG_LOCAL_IP --remote $WG_PEER_IP --interval 1000"
elif [ "$EXE" == "cndp-packet" ]; then
	RUST_EXE=cndp-packet
	TRAFFIC_GEN_MAC=f8:f2:1e:33:52:e1
	MODE=${3:-send}
	if [ "$MODE" == "send" ]; then
		ARGS="--disable-drop-privileges --device rsuwg0 --traffic-gen-mac $TRAFFIC_GEN_MAC --send"
	else
		ARGS="--disable-drop-privileges --device rsuwg0 --traffic-gen-mac $TRAFFIC_GEN_MAC"
	fi
else
	RUST_EXE=wireguard-rs
	ARGS="--disable-drop-privileges rsuwg0"
fi

RUN="sudo -E LD_LIBRARY_PATH=$LD_LIBRARY_PATH RUST_LOG=$RUST_LOG_VAL `which cargo` run --bin $RUST_EXE"
#RUN="sudo -E LD_LIBRARY_PATH=$LD_LIBRARY_PATH RUST_LOG=$RUST_LOG_VAL `which cargo` run --bin $RUST_EXE"
if [ "$BUILD" == "debug" ]; then
	$RUN -- $ARGS
else
	$RUN --release -- $ARGS
fi
# Wait for interface to come up.
sleep 3

# Set wireguard interface ip addr.
sudo ip addr add $WG_LOCAL_IP/24 dev rsuwg0
# Set private key in wg interface.
sudo wg set rsuwg0 private-key $PRIVATE_KEY
# Set MTU.
sudo ip link set mtu $WG_MTU dev rsuwg0
# Set listening port.
sudo wg set rsuwg0 listen-port $WG_LOCAL_LISTEN_PORT
# Set remote peer public key, wireguard ip, endpoint and listen port.
if [ "$EXE" == "cndp-packet" ]; then
	WG_PEER_IP1=10.5.5.1 # Remote IP used by packet generator.
	ALLOWED_IPS=$WG_PEER_IP/32,$WG_PEER_IP1/32
else
	ALLOWED_IPS=$WG_PEER_IP/32
fi
#sudo wg set rsuwg0 peer $WG_PEER_PUBLIC_KEY allowed-ips $ALLOWED_IPS endpoint $WG_PEER_ENDPOINT
sudo wg set rsuwg0 peer $WG_PEER_PUBLIC_KEY allowed-ips 0.0.0.0/0 endpoint $WG_PEER_ENDPOINT
# Enable wireguard interface.
sudo ip link set rsuwg0 up
# Wait for interface to come up.
sleep 3
stty sane

**Comment by liuzhen111** [comment]
@manojgop yes，i set the private keys in local wg interface.
    PRIVATE_KEY="/etc/private-key"
    ……
    sudo wg set rsuwg0 private-key $PRIVATE_KEY
    # Set MTU.
    sudo ip link set mtu $WG_MTU dev rsuwg0

**Comment by liuzhen111** [comment]
@manojgop The problem has been resolved, the server port cannot be modified, and only 5500 can be used

**Comment by manojgop** [comment]
> @manojgop The problem has been resolved, the server port cannot be modified, and only 5500 can be used

You could modify the script `cndprustwg.sh` to use the required port

**Comment by liuzhen111** [comment]
@manojgop I modified the cndprustwg.sh file before:
WG_PEER_LISTEN_PORT=8899; 
but actually can not connect.
 Then just revert to port 5500 and it can connect successfully.
Is it necessary to modify the port to 8899 when applying patch before cargo build?

**Comment by liuzhen111** [comment]
![Uploading IMG_1541.jpeg…]()

**Comment by liuzhen111** [comment]
![IMG_1541](https://github.com/CloudNativeDataPlane/cndp/assets/13791154/1caf359c-e4c9-4636-9e1f-73c30fd81dc5)

**Comment by liuzhen111** [comment]
@manojgop Hello, the server has been shut down for a few hours and restarted. The configuration has not changed, but it cannot be connected again, which is very strange.

**Comment by liuzhen111** [comment]
debug:
[2023-07-05T07:07:41Z DEBUG wireguard_rs::wireguard::router::peer] no key encryption key available
[2023-07-05T07:07:41Z DEBUG wireguard_rs::wireguard::router::peer] request new key
[2023-07-05T07:07:41Z DEBUG wireguard_rs::wireguard::workers] TUN worker, router returned Ok(())
[2023-07-05T07:07:42Z DEBUG wireguard_rs::wireguard::timers] Handshake for PeerHandle(format: TODO) did not complete after 5 seconds, retrying (try 0)
[2023-07-05T07:07:42Z DEBUG wireguard_rs::wireguard::workers] wireguard(5e4e70f5) : handshake worker, new handshake requested for PeerHandle(format: TODO)
[2023-07-05T07:07:42Z DEBUG wireguard_rs::wireguard::handshake::noise] create initiation
[2023-07-05T07:07:43Z DEBUG wireguard_rs::wireguard::workers] TUN worker, IP packet of 84 bytes (MTU = 1420)
[2023-07-05T07:07:43Z DEBUG wireguard_rs::wireguard::router::peer] no key encryption key available
[2023-07-05T07:07:43Z DEBUG wireguard_rs::wireguard::router::peer] request new key
[2023-07-05T07:07:43Z DEBUG wireguard_rs::wireguard::workers] TUN worker, router returned Ok(())
[2023-07-05T07:07:44Z DEBUG wireguard_rs::wireguard::workers] TUN worker, IP packet of 84 bytes (MTU = 1420)

**Comment by liuzhen111** [comment]
@manojgop I have compressed the relevant configuration files into a zip file. Could you please help me check if there are any issues? Thank you

**Comment by manojgop** [comment]
Could you check if the traffic is hitting the required queue --> `watch -n1 -d "sudo ethtool -S ens6f1 | grep packets | column"`

**Comment by liuzhen111** [comment]
@manojgop 
<img width="1233" alt="image" src="https://github.com/CloudNativeDataPlane/cndp/assets/13791154/225d5b52-f59d-472e-89ef-ff3670bb0324">
ethtool -U ens6f1 flow-type udp4  src-ip 192.168.60.2      dst-ip 192.168.60.1     action 1  loc 1
ethtool -U ens6f1 flow-type udp4  src-ip 192.168.60.1      dst-ip 192.168.60.2     action 2  loc 2
---------------------------------------
tx-1.packets: 0  And rx-1.packets: 0

**Comment by manojgop** [comment]
So looks like no packets reaching queue 1

**Comment by liuzhen111** [comment]
Yes, I'm also very strange. Also, I would like to ask if there were any settings errors in the configuration file in the zip package in yesterday's email?

**Comment by liuzhen111** [comment]
@manojgop Hello, what is the operating system version and kernel version you used for testing?

**Comment by liuzhen111** [comment]
tail -f /var/log/syslog
<img width="1013" alt="image" src="https://github.com/CloudNativeDataPlane/cndp/assets/13791154/e1d0b110-0635-4a3a-9c2d-303f909a1661">

**Comment by liuzhen111** [comment]
The current test result is that the data packet was not sent out through queue 1. 
As a result, Wireguard was unable to connect successfully, and the debug :"wireguard::router::peer] no key encryption key available".

**Comment by manojgop** [comment]
Once you ping remote wireguard interface IP, it'll request a new key. As you can see in following logs you can see "no key encryption key available" and then "request new key".

```
    Finished dev [optimized + debuginfo] target(s) in 45.61s
     Running `target/debug/wireguard-rs --disable-drop-privileges rsuwg0`
[2023-07-07T05:35:23Z INFO  wireguard_rs] Starting rsuwg0 WireGuard device.
[2023-07-07T05:35:23Z DEBUG wireguard_rs::wireguard::workers] wireguard(757399cf) : handshake worker, started
[2023-07-07T05:35:23Z DEBUG wireguard_rs::wireguard::workers] wireguard(757399cf) : handshake worker, started
[2023-07-07T05:35:23Z DEBUG wireguard_rs::wireguard::workers] wireguard(757399cf) : handshake worker, started
[2023-07-07T05:35:23Z DEBUG wireguard_rs::wireguard::workers] wireguard(757399cf) : handshake worker, started
[2023-07-07T05:35:23Z DEBUG wireguard_rs::platform::linux::tun] netlink, fetch event (fd = 5)
[2023-07-07T05:35:24Z DEBUG wireguard_rs::platform::linux::tun] netlink, received message (80 bytes)
[2023-07-07T05:35:24Z DEBUG wireguard_rs::configuration::uapi] UAPI, Result of operation: Err(IOError)
[2023-07-07T05:35:24Z DEBUG wireguard_rs::configuration::uapi] UAPI, Set operation
[2023-07-07T05:35:24Z INFO  wireguard_rs::configuration::config] configuration, set private key
[2023-07-07T05:35:24Z DEBUG wireguard_rs::wireguard::router::device] Clear sending keys
[2023-07-07T05:35:24Z DEBUG wireguard_rs::configuration::uapi] UAPI, Result of operation: Ok(())
[2023-07-07T05:35:24Z DEBUG wireguard_rs::platform::linux::tun] netlink, received message (1372 bytes)
[2023-07-07T05:35:24Z INFO  wireguard_rs] Tun down
[2023-07-07T05:35:24Z INFO  wireguard_rs::configuration::config] configuration, set device down
[2023-07-07T05:35:24Z DEBUG wireguard_rs::platform::linux::tun] netlink, fetch event (fd = 5)
[2023-07-07T05:35:25Z DEBUG wireguard_rs::configuration::uapi] UAPI, Result of operation: Err(IOError)
[2023-07-07T05:35:25Z DEBUG wireguard_rs::configuration::uapi] UAPI, Set operation
[2023-07-07T05:35:25Z DEBUG wireguard_rs::configuration::uapi] UAPI, Result of operation: Ok(())
[2023-07-07T05:35:25Z DEBUG wireguard_rs::configuration::uapi] UAPI, Result of operation: Err(IOError)
[2023-07-07T05:35:25Z DEBUG wireguard_rs::configuration::uapi] UAPI, Set operation
[2023-07-07T05:35:25Z DEBUG wireguard_rs::configuration::uapi] UAPI, Result of operation: Ok(())
[2023-07-07T05:35:25Z DEBUG wireguard_rs::platform::linux::tun] netlink, received message (1376 bytes)
[2023-07-07T05:35:25Z INFO  wireguard_rs] Tun up (mtu = 1420)
[2023-07-07T05:35:25Z INFO  wireguard_rs::configuration::config] configuration, set device up
[2023-07-07T05:35:25Z INFO  wireguard_rs::platform::linux::cndp::udp] Wireguard called bind at port 5400
[2023-07-07T05:35:25Z DEBUG wireguard_rs::wireguard::workers] TUN worker, IP packet of 1 bytes (MTU = 0)
manoj@qct-4:~/wireguard/cndp/wireguard-rs$ [2023-07-07T05:35:26Z DEBUG wireguard_rs::platform::linux::cndp::udp] netdev = enp134s0
[2023-07-07T05:35:26Z DEBUG wireguard_rs::platform::linux::cndp::udp] ipv4_addr = Some(48.0.0.154)
[2023-07-07T05:35:26Z DEBUG wireguard_rs::platform::linux::cndp::udp] src_mac = Some(40:a6:b7:78:3f:ec)
[2023-07-07T05:35:26Z DEBUG wireguard_rs::platform::linux::tun] netlink, fetch event (fd = 5)
[2023-07-07T05:35:26Z DEBUG wireguard_rs::platform::linux::tun] netlink, received message (72 bytes)
[2023-07-07T05:35:26Z DEBUG wireguard_rs::platform::linux::tun] netlink, received message (1396 bytes)
[2023-07-07T05:35:26Z DEBUG wireguard_rs::platform::linux::tun] netlink, received message (1408 bytes)
[2023-07-07T05:35:29Z DEBUG wireguard_rs::wireguard::workers] TUN worker, IP packet of 48 bytes (MTU = 1420)
[2023-07-07T05:35:29Z DEBUG wireguard_rs::wireguard::workers] TUN worker, router returned Err(NoCryptoKeyRoute)
[2023-07-07T05:35:38Z DEBUG wireguard_rs::wireguard::workers] TUN worker, IP packet of 48 bytes (MTU = 1420)
[2023-07-07T05:35:38Z DEBUG wireguard_rs::wireguard::workers] TUN worker, router returned Err(NoCryptoKeyRoute)
[2023-07-07T05:35:48Z DEBUG wireguard_rs::wireguard::workers] TUN worker, IP packet of 84 bytes (MTU = 1420)
[2023-07-07T05:35:48Z DEBUG wireguard_rs::wireguard::router::peer] no key encryption key available
[2023-07-07T05:35:48Z DEBUG wireguard_rs::wireguard::router::peer] request new key
[2023-07-07T05:35:48Z DEBUG wireguard_rs::wireguard::workers] TUN worker, router returned Ok(())
[2023-07-07T05:35:48Z DEBUG wireguard_rs::wireguard::workers] wireguard(757399cf) : handshake worker, new handshake requested for PeerHandle(format: TODO)
[2023-07-07T05:35:48Z DEBUG wireguard_rs::wireguard::handshake::noise] create initiation
[2023-07-07T05:35:48Z DEBUG wireguard_rs::platform::linux::cndp::udp] iface_name: enp134s0, dst_ipv4 = 48.0.0.155
[2023-07-07T05:35:48Z DEBUG wireguard_rs::platform::linux::tun] netlink, received message (1396 bytes)
[2023-07-07T05:35:48Z DEBUG wireguard_rs::platform::linux::cndp::packet] Sent ARP request
[2023-07-07T05:35:48Z DEBUG wireguard_rs::platform::linux::cndp::packet] Received ARP reply
[2023-07-07T05:35:48Z DEBUG wireguard_rs::platform::linux::tun] netlink, received message (1396 bytes)
[2023-07-07T05:35:48Z DEBUG wireguard_rs::platform::linux::cndp::udp] dst mac from ARP = 40:a6:b7:68:95:d4
[2023-07-07T05:35:48Z DEBUG wireguard_rs::platform::linux::cndp::udp] stored dst mac in map
[2023-07-07T05:35:48Z DEBUG wireguard_rs::platform::linux::cndp::udp] Read bulk 1 UDP Packets at time 1688708148096391
[2023-07-07T05:35:48Z DEBUG wireguard_rs::platform::linux::cndp::udp] Read cndp_ethernet_packet = CndpPacket [
                                src_mac: Some(40:a6:b7:68:95:d4), dst_mac: Some(40:a6:b7:78:3f:ec),
                                src_ip: Some(48.0.0.155), dst_ip: Some(48.0.0.154),
                                src_port: Some(5500), dst_port: Some(5400)
                               ]
```

**Comment by liuzhen111** [comment]
Yes. But according to the "sudo wg "command, there are public key 。
<img width="593" alt="image" src="https://github.com/CloudNativeDataPlane/cndp/assets/13791154/a16d912c-f80f-4582-a2e5-ee785cd8b870">
=================================================================
Currently, I am using Ubuntu 22 for testing,  the kernel version 5.15.0-60-generic
， it has the same issue as when using Ubuntu 20.
-----------------------------
root@ubuntu-22:~/driver/i40e-2.22.20/src# ethtool -i ens6f1
driver: i40e
version: 2.22.20
firmware-version: 8.15 0x800096c1 20.0.17
expansion-rom-version:
bus-info: 0000:02:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

root@ubuntu-22:~/driver/i40e-2.22.20/src# uname -r
5.15.0-60-generic

**Comment by manojgop** [comment]
Both ends will derive session keys from public keys using wireguard handshake protocol.

**Comment by manojgop** [comment]
My system has Ubuntu 22.04 and 5.11.0-18-generic kernel

**Comment by liuzhen111** [comment]
thanks you!
Is the network card driver using the built-in kernel or manually installed network card driver? 
If it is manually installed, what is the network card driver version?
Is the source code address of wireguard cndp the following one?
Git clone https://github.com/WireGuard/wireguard-rs.git

**Comment by liuzhen111** [comment]
Can you send me a copy of the configuration file you are currently using.
Including: cndprustwg.sh, fwd.jsonc, wg_ Cndp.toml
My email is liuzhen111@gmail.com
thank you

**Comment by liuzhen111** [comment]
The network adapter uses the kernel driver, and there are errors in syslog:

root@ubuntu-22:/var/by# ethtool -i ens6f1
driver: i40e
version: 5.15.0-60-generic
firmware-version: 8.15 0x800096c1 20.0.17
expansion-rom-version:
bus-info: 0000:02:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes

------------------------
tailf -f /var/log/syslog

Jul  7 06:41:21 ubuntu-22 kernel: [ 9642.826694] i40e 0000:02:00.1: Registered XDP mem model MEM_TYPE_XSK_BUFF_POOL on Rx ring 1
Jul  7 06:41:21 ubuntu-22 kernel: [ 9642.826990] i40e 0000:02:00.1: Failed to allocate some buffers on AF_XDP ZC enabled Rx ring 1 (pf_q 1)
Jul  7 06:41:21 ubuntu-22 kernel: [ 9642.913722] i40e 0000:02:00.1: Registered XDP mem model MEM_TYPE_XSK_BUFF_POOL on Rx ring 2
Jul  7 06:41:21 ubuntu-22 kernel: [ 9642.913925] i40e 0000:02:00.1: Failed to allocate some buffers on AF_XDP ZC enabled Rx ring 2 (pf_q 2)
Jul  7 06:41:22 ubuntu-22 kernel: [ 9643.656189] device rsuwg0 entered promiscuous mode
Jul  7 06:41:22 ubuntu-22 kernel: [ 9643.738008] i40e 0000:02:00.1: VSI seid 389 XDP Tx ring 0 disable timeout
Jul  7 06:41:23 ubuntu-22 kernel: [ 9644.262780] i40e 0000:02:00.1: Registered XDP mem model MEM_TYPE_XSK_BUFF_POOL on Rx ring 1
Jul  7 06:41:23 ubuntu-22 kernel: [ 9644.263070] i40e 0000:02:00.1: Failed to allocate some buffers on AF_XDP ZC enabled Rx ring 1 (pf_q 1)
Jul  7 06:41:23 ubuntu-22 kernel: [ 9644.333777] i40e 0000:02:00.1: Registered XDP mem model MEM_TYPE_XSK_BUFF_POOL on Rx ring 2
Jul  7 06:41:23 ubuntu-22 kernel: [ 9644.334063] i40e 0000:02:00.1: Failed to allocate some buffers on AF_XDP ZC enabled Rx ring 2 (pf_q 2)

**Comment by manojgop** [comment]
> Can you send me a copy of the configuration file you are currently using. Including: cndprustwg.sh, fwd.jsonc, wg_ Cndp.toml My email is [liuzhen111@gmail.com](mailto:liuzhen111@gmail.com) thank you

[wg_cndp_config.zip](https://github.com/CloudNativeDataPlane/cndp/files/11982311/wg_cndp_config.zip)

**Comment by KeithWiles** [comment]
The errors above are not really errors but information messages. I am assuming these messages appear each time you start the application, if not then maybe we have an issue. If they are happening while running the application then you may not have enough buffers allocated.

Buffers can be consumed for Rx and Tx AF_XDP rings, plus they can be on the CQ/FQ rings and mempool cache, plus the application could be holding onto a large number of buffers as well. Find out how big the Rx/Tx/FQ/CQ rings times the number of AF_XDP sockets are in size than double or triple the number of mbufs.

But if these message only appear at startup, but not while running then you do not have a problem with the number of buffers. Running the AF_XDP sample application could help determine if things are really working, but the WG example is not.

**Comment by liuzhen111** [comment]
I switched the ethtool -N rule to:
sudo ethtool -U ens6f1 flow-type udp4  src-ip 192.168.60.2     dst-ip 192.168.60.1     action 2  loc 1
sudo ethtool -U ens6f1 flow-type udp4  src-ip 192.168.60.1      dst-ip 192.168.60.2     action 1  loc 2
but:
<img width="1009" alt="image" src="https://github.com/CloudNativeDataPlane/cndp/assets/13791154/648d6d67-b1e7-4ae2-aecb-49b2c29b8bea">

Still only queue 2 has packets on it, which is very surprising

**Comment by KeithWiles** [comment]
Please make sure you have removed all of the old rules, which I assume you have done already.

I have had some problems in the past with drivers not really supporting all of the ethtool configuration options, but normally I would get an error when setting the rules and that does not seem to be the problem here.

If you configure ethtool to only send packets to 1 using something like `sudo ethtool -N ens6f1 flow-type udp4 dst-port 5678 action 1` pick a dst-port that works or just redirect all udp4 packets to 1 and see if they are being sent to 1.

I did not see the CNDP .jsonc file you are using, please post it here as sending things via email can get blocked.

**Comment by liuzhen111** [comment]
@KeithWiles 
[fwd.jsonc.zip](https://github.com/CloudNativeDataPlane/cndp/files/11982836/fwd.jsonc.zip)

**Comment by liuzhen111** [comment]
I reset ethtool as follows:
sudo ethtool -K ens6f1 ntuple off
sudo ethtool -K ens6f1 ntuple on
sudo ethtool -N ens6f1 flow-type udp4   action 1 loc 1

<img width="1087" alt="image" src="https://github.com/CloudNativeDataPlane/cndp/assets/13791154/be30f1be-3c2d-421e-925c-20e02c0ccd15">

**Comment by KeithWiles** [comment]
I would change to the following, just to increase the number of mbufs for each port. It may not be this problem, but I think it needs to be more.

```
    "umems": {
        "umem0": {
            "bufcnt": 64, // <--
            "bufsz": 2,
            "mtype": "2MB",
            "regions": [
                32, // <--
                32 // <--
            ],
            "rxdesc": 0,
            "txdesc": 0,
            "description": "UMEM Description 0"
        }
    }
```

**Comment by KeithWiles** [comment]
In the above ethtool output you have packets on RX-1 and TX-2. Meaning a unidirectional traffic are being received on rx-1 and sent to tx-2. Are you sending traffic in the other direction?

**Comment by liuzhen111** [comment]
@KeithWiles Server B is linux normal wireguard(without cndp)

**Comment by liuzhen111** [comment]
"umems": {
        "umem0": {
            "bufcnt": 64,
            "bufsz": 2,
            "mtype": "2MB",
            "regions": [
                32,
                32
            ],
            "rxdesc": 0,
            "txdesc": 0,
            "description": "UMEM Description 0"
        }
    },
Just modified the configuration here according to your above, but it still doesn't connect.
------------
One night before, I accidentally connected once, and the only connection was successful.
At that time, only port 5500 can be used to connect to server B. If port 8899 or other ports are used, the connection fails.
Then, the server shuts down for one night, only to be disconnected the next day

**Comment by liuzhen111** [comment]
> 在上面的 ethtool 输出中，您在 RX-1 和 TX-2 上有数据包。这意味着 rx-1 上接收单向流量并将其发送到 tx-2。您是否向另一个方向发送流量？

At that point, I was just using the ping command
 ping  10.5.5.1

**Comment by KeithWiles** [comment]
I assume ARP resolves to the correct IP and MAC addresses on both machines after the ping command?

**Comment by KeithWiles** [comment]
Setup a ping between the two machines to run continuously, then try WG and see if that helps. Assuming the two machines are ping correctly.

**Comment by liuzhen111** [comment]
> Setup a ping between the two machines to run continuously, then try WG and see if that helps. Assuming the two machines are ping correctly. Ping from both machines at the same time. Just having one should work, but just to verify traffic is moving between the two machines while trying the WG application.

I just tested it. It's good. After the "./cndprustwg.sh "command is executed.
Then ping each other from both ends at the same time, and you can ping each other.

**Comment by liuzhen111** [comment]
<img width="539" alt="image" src="https://github.com/CloudNativeDataPlane/cndp/assets/13791154/ac67f9f8-69d0-4811-9d7b-02841801bc82">
After about 20 packets, they can't ping each other again.
Re-execute./cndprustwg.sh and ping each other again for a short time.

**Comment by KeithWiles** [comment]
Does the ARP entries age out after it stops? `arp -n`

**Comment by liuzhen111** [comment]
> 

yes ，
<img width="655" alt="image" src="https://github.com/CloudNativeDataPlane/cndp/assets/13791154/68577051-201e-4f52-ab7a-36a30e6511c4">
When ping is aborted, it is displayed here
192.168.60.1   (incomplete)   ens6f1

**Comment by liuzhen111** [comment]
> I see, this means something is deleting the ARP entries or they are arging out some how.

The problem has been resolved with a replacement of the peer server and now ping is fine.

**Comment by liuzhen111** [comment]
@manojgop Now the two servers can be used normally in the same LAN.
Now I want to use the wireguard (with cndp) on the public network, can you support it?
Or do the two servers have to be on the same subnet?

**Comment by liuzhen111** [comment]
> I see, this means something is deleting the ARP entries or they are arging out some how.

thank you very much!

**Comment by liuzhen111** [comment]
@KeithWiles  thank you very much!

**Comment by liuzhen111** [comment]
@manojgop 
Now the two servers can be used normally in the same LAN.
Now I want to use the wireguard (with cndp) on the public network, can it  support?
Or do the two servers have to be on the same subnet?
