### ISSUE TITLE
PMD Constructors Priority should be less than max.

### ISSUE THREAD

**Issue by jalalmostafa** [CloudNativeDataPlane/cndp#360]
The current configuration sets the priority of PMDs constructors to 65535 (the maximum supported by compilers):

https://github.com/CloudNativeDataPlane/cndp/blob/f8f98377462abab0bba882aed59e3d4043abe48f/lib/core/pktdev/pktdev_driver.h#L55-L60

I believe it should be less than max as it does not leave any possible values for the CNDP users to use.
Running the user constructors/destructors also with priority max does not guarantee that the user's constructors will run after the PMD constructors. An example of such a use case is a shared library wrapping CNDP and trying to initialize its context.
Rather I suggest an explicit constructor/destructor priority instead of using the maximum value and leaving the wider range to the user e.g. by considering using only half of the priority spectrum

```c
#define CNE_PRIORITY_LAST 32768
```

or even a dedicated PMD priority

```c
#define CNE_PRIORITY_PMD 30000
#define CNE_PRIORITY_LAST 32768
``` 
If you agree, I can open a PR.

**Comment by KeithWiles** [comment]
Thanks the suggestion does look reasonable, please create a PR.

**Comment by KeithWiles** [comment]
Please us a specific PMD priority, thanks.
