### ISSUE TITLE
Minor doc issues with libbpf installation instructions

### ISSUE THREAD

**Issue by john-mcnamara-intel** [CloudNativeDataPlane/cndp#37]
I followed the CNDP instructions here: https://github.com/CloudNativeDataPlane/cndp/blob/main/INSTALL.md but had an issue with the libbpf step:

### Install libbpf from source

```bash
https_proxy="https://user:password@proxy.server:port" git clone https://github.com/libbpf/libbpf.git
cd libbpf
git checkout ...
make -C src
sudo make -C src install
```
There are 2 issues here. First I don't think the `https_proxy` needs to be there. Secondly this gives a version of libbpf (0.8.0/??) which seems incompatible with cndp:

```bash
$ make
"/work/cndp/tools/cne-build.sh" build
Build environment variables and paths:
  CNE_SDK_DIR     : /work/cndp
  CNE_TARGET_DIR  : usr/local
  CNE_BUILD_DIR   : /work/cndp/builddir
  CNE_DEST_DIR    : /work/cndp
  PKG_CONFIG_PATH : /usr/lib64/pkgconfig
  build_path      : /work/cndp/builddir
  target_path     : /work/cndp/usr/local

>>> Release build in '/work/cndp/builddir'
>>> Ninja build in '/work/cndp/builddir' buildtype='release'
usage: meson [-h] {setup,configure,dist,install,introspect,init,test,wrap,subprojects,help,rewrite,compile,devenv} ...
meson: error: unrecognized arguments: 
ninja: Entering directory `/work/cndp/builddir'
[10/54] Compiling C object lib/core/xskdev/libcne_xskdev.so.p/xskdev.c.o
FAILED: lib/core/xskdev/libcne_xskdev.so.p/xskdev.c.o 
cc -Ilib/core/xskdev/libcne_xskdev.so.p -Ilib/core/xskdev -I../lib/core/xskdev -Ilib/include -I../lib/include -Ilib/core/osal -I../lib/core/osal -Ilib/core/log -I../lib/core/log -I. -I.. -Ilib/core/cne -I../lib/core/cne -Ilib/common/uds -I../lib/common/uds -Ilib/core/mmap -I../lib/core/mmap -Ilib/core/mempool -I../lib/core/mempool -Ilib/core/pktmbuf -I../lib/core/pktmbuf -I/usr/include/libnl3 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -Werror -O3 -g -Wno-pedantic -Wcast-qual -Wdeprecated -Wformat-nonliteral -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-address-of-packed-member -Wno-packed-not-aligned -Wno-missing-field-initializers -D_GNU_SOURCE -include cne_build_config.h -march=native -DCC_AVX2_SUPPORT -fPIC -MD -MQ lib/core/xskdev/libcne_xskdev.so.p/xskdev.c.o -MF lib/core/xskdev/libcne_xskdev.so.p/xskdev.c.o.d -o lib/core/xskdev/libcne_xskdev.so.p/xskdev.c.o -c ../lib/core/xskdev/xskdev.c
../lib/core/xskdev/xskdev.c: In function 'configure_busy_poll':
../lib/core/xskdev/xskdev.c:122:5: error: 'xsk_socket__fd' is deprecated: libbpf v0.7+: AF_XDP support deprecated and moved to libxdp [-Werror=deprecated-declarations]
  122 |     int fd            = xsk_socket__fd(rxq->xsk);
      |     ^~~
In file included from ../lib/core/xskdev/xskdev.h:11,
                 from ../lib/core/xskdev/xskdev.c:27:
/usr/include/bpf/xsk.h:257:5: note: declared here
  257 | int xsk_socket__fd(const struct xsk_socket *xsk);
      |     ^~~~~~~~~~~~~~

```
This is a useful hint buried there but it isn't obvious:

```
 error: 'xsk_socket__fd' is deprecated: libbpf v0.7+: AF_XDP
```

In order to get cndp to compile I had to use libbpf 0.6.1. I don't know if that is the preferred version but it worked.

```bash
cd libbfp
git checkout v0.6.1
make -C src && sudo make -C src install
```

**Comment by KeithWiles** [comment]
Yes 0.6.1 is preferred version here. Plus the proxy is not required anymore.

We need to use version 0.6.1 until we move over to using libxdp, then libbpf version above 0.6.1 should work.

**Comment by jeffreybshaw** [comment]
Thanks John. I actually just noticed this yesterday that the INSTALL.md doesn't mention a libbpf version.

Really you can use any libbpf version < 0.7. Our GitHub [CI](https://github.com/CloudNativeDataPlane/cndp/blob/main/.github/workflows/smoke.yml#L26), example Dockerfile, and Ansible install scripts use 0.3.0, which is pretty old at this point. We're planning to update to 0.5.0 which is the version packaged with Ubuntu 22.04, since I expect many people will probably just ``apt-get install -y libbpf``.

Probably in the next release we'd like to announce that we're moving away from libbpf in favor of libbpf + libxdp so we don't have the version mismatch issues. Then at some point in the future we *only* support a combination of libbpf + libxdp, rather than the older libbpf versions.

Oh, and the https_proxy is still required, but only if you're behind a proxy :)

**Comment by KeithWiles** [comment]
Do we need to still describe building the Linux kernel source as that is not needed for standard distros?
