### ISSUE TITLE
update github actions to allow it to create pull requests

### ISSUE THREAD

**Issue by maryamtahhan** [CloudNativeDataPlane/cndp#398]
`  Error: GitHub Actions is not permitted to create or approve pull requests.`

@KeithWiles can you update the permissions as shown here:  https://github.com/orgs/community/discussions/27689#discussioncomment-3285687

**Comment by KeithWiles** [comment]
Hi Maryam, I think I changed it. Give it a shot thanks

**Comment by KeithWiles** [comment]
I changed it to have read/write permissions. Lets see if that works now.

**Comment by KeithWiles** [comment]
HI Maryam, I think I added the pre-commit CI

**Comment by maryamtahhan** [comment]
> HI Maryam, I think I added the pre-commit CI

Thanks Keith
