### ISSUE TITLE
Rust language bindings and directory structure needs cleanup and restructure

### ISSUE THREAD

**Issue by maryamtahhan** [CloudNativeDataPlane/cndp#88]
Hi Folks
I recently started looking through the Rust language bindings for CNDP and ran into a few issues. Following the readme things don't work out of the box. In addition the directory structure is completely confusing (there's no real structure to what's an example vs what's the set of libraries I can use as part of my Rust application). Also I believe the naming should be libcndp-sys for the directory that contains the language bindings (cne is only a small library set of what CNDP has to offer).

The current dir structure is shown below:
```
.
├── README.md
├── bindings
│   ├── cne
│   │   ├── Cargo.toml
│   │   ├── README.md
│   │   ├── examples
│   │   │   └── loopback
│   │   │       ├── Cargo.toml
│   │   │       ├── run.sh
│   │   │       └── src
│   │   │           └── main.rs
│   │   ├── fwd.jsonc
│   │   ├── run_test.sh
│   │   └── src
│   │       ├── config.rs
│   │       ├── error.rs
│   │       ├── instance.rs
│   │       ├── lib.rs
│   │       ├── packet.rs
│   │       ├── port.rs
│   │       └── util.rs
│   ├── cne-sys
│   │   ├── Cargo.toml
│   │   ├── README.md
│   │   ├── build.rs
│   │   └── src
│   │       ├── bindings
│   │       │   ├── bindings.c
│   │       │   ├── bindings.h
│   │       │   ├── meson.build
│   │       │   └── wrapper.h
│   │       └── lib.rs
│   └── examples
│       └── echo_server
│           ├── Cargo.toml
│           ├── fwd.jsonc
│           ├── run.sh
│           └── src
│               └── main.rs
├── helloworld
│   └── main.rs
├── mmap
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
├── mmap-cndp
│   ├── Cargo.toml
│   ├── build.rs
│   ├── src
│   │   └── lib.rs
│   └── wrapper.h
├── pktfwd
│   ├── Cargo.toml
│   ├── build.rs
│   ├── fwd.jsonc
│   ├── jcfg_parse
│   │   ├── fwd.h
│   │   ├── meson.build
│   │   ├── parse-jsonc.c
│   │   ├── rust_helper.c
│   │   ├── rust_helper.h
│   │   └── stats.c
│   ├── runcmd.sh
│   ├── src
│   │   ├── cndp.rs
│   │   ├── main.rs
│   │   ├── packet.rs
│   │   └── util.rs
│   └── wrapper.h
├── ring_test
│   ├── Cargo.toml
│   ├── build.rs
│   ├── src
│   │   ├── lib.rs
│   │   └── main.rs
│   └── wrapper.h
└── wireguard
    └── patch
        ├── 0001-Integrate-CNDP-Cloud-Native-Data-Plane-with-Wireguar.patch
        ├── 0002-Rename-variable-private-to-priv_-to-fix-build-error.patch
        └── 0003-Remove-extra-argument-from-pktmbuf_dump.patch
```

Finally - there's only a handful of APIs that have been converted to Rust and the naming is separate to the C libraries - so tracking what's where is going to be difficult.

Is there a plan to cleanup the Rust implementation and port more libraries?

**Comment by maryamtahhan** [comment]
+1 for the higher layer APIs to hide the binding details. But I still think from a bindings POV/level it would be good to have some level of alignment as libraries will need to be maintained over time. so at least a mapping or having similar namings could be useful. 

Yeah sure - we can setup sometime and drill down on this in order to get it into shape

**Comment by manojgop** [comment]
There are two Rust crates.
 
1.	Bindings crate – This package is currently named as cndp-cne-sys. This is low-level library (low level Rust interface to expose a minimal low-level C interface to Rust). In Rust terminology bindings crate are called sys crates.
2.	High level Rust API – This package is currently named as cndp-cne. This uses low level cndp-cne-sys crate. There is an examples directory under this with a simple app to show usage of high level API. This is consistent with many rust high level library crates which includes an example directory within a library crate.
3.	lang/rs/bindings/examples – Top level examples directory. This has more elaborate example applications (eg: echo server) which uses high level Rust (cndp-cne) API crate. I would prefer example applications to be kept under lang/rs/examples. Let's discuss.

**Comment by manojgop** [comment]
1. Other directories like hello_world, mmap, mmap_cndp we can delete.
2.  Existing pktfwd example I'll refactor to use high level Rust APIs.
3. I'm modifying Wireguard example to use high level Rust APIs.

**Comment by maryamtahhan** [comment]
> 1. Other directories like hello_world, mmap, mmap_cndp we can delete.
Great
> 2. Existing pktfwd example I'll refactor to use high level Rust APIs.
> 3. I'm modifying Wireguard example to use high level Rust APIs.
so let's talk about structure of dirs...

```
.
├── bindings
│   ├── cne-sys
├── apis
│   ├── cne
├── examples
│   ├── pktfwd

```

or something along those lines. Also one should be able to cargo build from the top level dir rather then each piece individually


I've verified that there are two issues with the build for the bindings:

- if you build and install CNDP locally (not in a system path) --> this build fails 100% of the time
- also there's an issue in the bindings meson.build or pkgconfig for CNDP... the libdir (shown below) is not where libcndp is found (it's installed @ '/usr/local/lib/x86_64-linux-gnu'). You also need to modify /etc/ld.so.conf.d/x86_64-linux-gnu.conf  to include the right library paths to link to

```
# cat /usr/local/lib/pkgconfig/libcndp.pc 
prefix=/usr/local
libdir=${prefix}/lib64
includedir=${prefix}/include
...
```

**Comment by manojgop** [comment]
1) Aya also seem to use sys crate approach (called aya-gen). But looks like its used as an internal dependency and not exposed as public
2) Do we want to publish low level cndp-cne-sys crate or only high level cndp-cne crate ?
3) For example, [libbpf-sys](https://github.com/libbpf/libbpf-sys) is a Rust binding API for libbpf.  But [libbpf-rs](https://github.com/libbpf/libbpf-rs) is a safe, idiomatic, and opinionated wrapper around libbpf-sys. Similarly [afxdp](https://github.com/aterlo/afxdp-rs) and [xsk-rs](https://github.com/DouglasGray/xsk-rs) are examples of high level Rust API library built using libbpf-sys.
4) If we want to publish only high level cndp-cne crate, we might need to keep `bindings` directory under `apis/cne` .  Aya also keeps aya-gen (low level bindings) under top level directory. May be @maryamtahhan can confirm this.

**Comment by maryamtahhan** [comment]
@manojgop I asked Dave and he suggested that the `libcne-sys` (language bindings) go into a crate and then the `cne` higher level API is another crate and both can be part of the same package

**Comment by manojgop** [comment]
> @manojgop I asked Dave and he suggested that the `libcne-sys` (language bindings) go into a crate and then the `cne` higher level API is another crate and both can be part of the same package

`cne-sys` is already a crate but it's in a separate package now. I can move `cne-sys` under higher level API 'cne` package. So we will plan to publish only high level `cne` crate in [https://crates.io](https://crates.io)

**Comment by manojgop** [comment]
@maryamtahhan Just to confirm. We can have atmost one library crate in a package --> [https://doc.rust-lang.org/book/ch07-01-packages-and-crates.html](https://doc.rust-lang.org/book/ch07-01-packages-and-crates.html). So both cne-sys and cne cannot be part of same package as both are library crate.  I guess what Dave meant would be to keep both cne-sys and cne in same workspace. Please confirm. Also since cne crate is dependent on cne-sys crate , inorder to publish cne high level API crate in crates.io, we also need a version of cne-sys to be published in crates.io. Cargo doesn't path dependency when publishing crates.  [https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies)

**Comment by manojgop** [comment]
If I do a dry run to publish cne high level crate we get below error
```
cargo publish --dry-run
    Updating crates.io index
error: all dependencies must have a version specified when publishing.
dependency `cndp-cne-sys` does not specify a version
Note: The published dependency will use the version from crates.io,
the `path` specification will be removed from the dependency declaration.
```

**Comment by maryamtahhan** [comment]
> @maryamtahhan Just to confirm. We can have atmost one library crate in a package 

yes they are separate packages

**Comment by maryamtahhan** [comment]
> If I do a dry run to publish cne high level crate we get below error. This is because cargo expects cne-sys also be in crates.io (with a version) and local path dependency is not allowed in publishing cne crate.
> 
> ```
> cargo publish --dry-run
>     Updating crates.io index
> error: all dependencies must have a version specified when publishing.
> dependency `cndp-cne-sys` does not specify a version
> Note: The published dependency will use the version from crates.io,
> the `path` specification will be removed from the dependency declaration.
> ```

If they are being built as separate crates then why wouldn't you publish them as separate crates?

our discussion previously was around answering the questions:

1. what's best practice in Rust?
2. can we publish things as 1 crate as we prefer not to expose the lower level APIs...

if there's an incompatibility between what we want and what's right/best practice then fall back to best practice

**Comment by manojgop** [comment]
1. If we prefer to publish only one high level API crate then we need to make bindings code also part of high level API package and then the high level crate becomes too big. The best practice suggested or followed by existing Rust projects is to split crates to smaller manageable crates where it's feasible to do so. 
2. Since we split Rust CNDP into two crates - low level bindings and high level API crates, we will have to publish both crates in crates.io.  I'm fine with publishing low level cne-sys crate in crates.io since it is only exposing Rust bindings APIs for existing CNDP C public APIs (subset of it).  High level cne crate is using low level cne-sys crate and it exposes high level APIs. Expectation is that most CNDP Rust applications will depend on only high level crate though technically applications could use low level crates as well.

Based on my understanding of Rust best practice and how crates/packages are organized, I would suggest we publish both crates.  cne-sys crate first followed by cne crate.

**Comment by KeithWiles** [comment]
@manojgop is the restructure complete now and can this one be closed?

**Comment by manojgop** [comment]
> @manojgop is the restructure complete now and can this one be closed?

Yes. I believe this can be closed

**Comment by KeithWiles** [comment]
Closing this one as it is done. If not please open a new issue.
